In [ ]:
import numpy as np


In [ ]:
from numpy import genfromtxt
data=genfromtxt('C:/Users/panindia/Desktop/Udemy/Computer-Vision-with-Python/DATA/bank_note_data.txt',delimiter=',')

In [ ]:
features=data[:,0:4]
labels=data[:,4]

In [ ]:
X=features 
y=labels

1372

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [ ]:
from sklearn.preprocessing import MinMaxScaler 
scaler_object=MinMaxScaler()


In [ ]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [ ]:
scaler_X_train=scaler_object.transform(X_train)
scaler_X_test=scaler_object.transform(X_test)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense 

model=Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit(scaler_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 2s - loss: 0.7063 - acc: 0.4527
Epoch 2/50
 - 0s - loss: 0.6969 - acc: 0.5495
Epoch 3/50
 - 0s - loss: 0.6908 - acc: 0.5495
Epoch 4/50
 - 0s - loss: 0.6868 - acc: 0.5495
Epoch 5/50
 - 0s - loss: 0.6829 - acc: 0.5495
Epoch 6/50
 - 0s - loss: 0.6783 - acc: 0.5517
Epoch 7/50
 - 0s - loss: 0.6727 - acc: 0.5909
Epoch 8/50
 - 0s - loss: 0.6649 - acc: 0.6192
Epoch 9/50
 - 0s - loss: 0.6565 - acc: 0.6529
Epoch 10/50
 - 0s - loss: 0.6488 - acc: 0.6681
Epoch 11/50
 - 0s - loss: 0.6407 - acc: 0.6768
Epoch 12/50
 - 0s - loss: 0.6310 - acc: 0.6823
Epoch 13/50
 - 0s - loss: 0.6191 - acc: 0.6823
Epoch 14/50
 - 0s - loss: 0.6016 - acc: 0.6844
Epoch 15/50
 - 0s - loss: 0.5793 - acc: 0.6910
Epoch 16/50
 - 0s - loss: 0.5605 - acc: 0.7160
Epoch 17/50
 - 0s - loss: 0.5413 - acc: 0.7345
Epoch 18/50
 - 0s - loss: 0.5227 - acc: 0.7519
Epoch 19/50
 - 0s - loss: 0.5044 - acc: 0.7704
Epoch 20/50
 - 0s - loss: 0.4857 - acc: 0.7889
Epoch 21/50
 - 0s - loss: 0.4681 - acc: 0.7965
Epoch 22/50
 - 0s - lo

In [ ]:
model.predict_classes(scaler_X_test)

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    

In [ ]:
model.metrics_names

['loss', 'acc']

In [ ]:
model.evaluate(x=scaler_X_test,y=y_test)

453/453 [==============================] - 0s 344us/step


[0.14736403397409858, 0.9668874172185431]

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report 

In [ ]:
predictions=model.predict_classes(scaler_X_test)

In [ ]:
confusion_matrix(y_test,predictions )

array([[254,   3],
       [ 12, 184]], dtype=int64)

In [ ]:
print(classification_report (y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.95      0.99      0.97       257
        1.0       0.98      0.94      0.96       196

avg / total       0.97      0.97      0.97       453



In [ ]:
model.save('name.h5')

In [ ]:
from keras.models import load_model

In [ ]:
new_model=load_model('name.h5')

In [ ]:
new_model.predict_classes(X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    